-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 02:13:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TallerMecanico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TallerMecanico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TallerMecanico` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema tallermecanico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tallermecanico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tallermecanico` DEFAULT CHARACTER SET utf8 ;
USE `TallerMecanico` ;

-- -----------------------------------------------------
-- Table `TallerMecanico`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `apellido` VARCHAR(120) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Anio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Anio` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Anio` (
  `idAnio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `anio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAnio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Marca` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Marca` (
  `idMarca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `Anio_idAnio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marca_Anio1_idx` (`Anio_idAnio` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Anio1`
    FOREIGN KEY (`Anio_idAnio`)
    REFERENCES `TallerMecanico`.`Anio` (`idAnio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Modelo` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Modelo` (
  `idModelo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `Marca_idMarca` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idModelo`),
  INDEX `fk_Modelo_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_Modelo_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `TallerMecanico`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Vehiculo` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Vehiculo` (
  `idVehiculo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `Modelo_idModelo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idVehiculo`),
  INDEX `fk_Vehiculo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Vehiculo_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `TallerMecanico`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `TallerMecanico`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Estado` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Estado` (
  `idEstado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` ENUM('PROCESO', 'ESPERA', 'FINALIZADO') NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Servicio` (
  `idServicio` INT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `Estado_idEstado` INT UNSIGNED NOT NULL,
  `kilometrage` INT UNSIGNED NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `TallerMecanico`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`vehiculo_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`vehiculo_servicio` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`vehiculo_servicio` (
  `Vehiculo_idVehiculo` INT UNSIGNED NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  INDEX `fk_vehiculo_servicio_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) VISIBLE,
  INDEX `fk_vehiculo_servicio_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_servicio_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `TallerMecanico`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehiculo_servicio_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `TallerMecanico`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`CostoManoObra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`CostoManoObra` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`CostoManoObra` (
  `idCostoManoObra` INT UNSIGNED NOT NULL,
  `CostoManoObra` DECIMAL(7,2) UNSIGNED NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idCostoManoObra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Mecanico` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Mecanico` (
  `idMecanico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `apellido` VARCHAR(120) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  `CostoManoObra_idCostoManoObra` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMecanico`),
  INDEX `fk_Mecanico_CostoManoObra1_idx` (`CostoManoObra_idCostoManoObra` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_CostoManoObra1`
    FOREIGN KEY (`CostoManoObra_idCostoManoObra`)
    REFERENCES `TallerMecanico`.`CostoManoObra` (`idCostoManoObra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Mecanico_Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Mecanico_Servicio` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Mecanico_Servicio` (
  `Servicio_idServicio` INT UNSIGNED NOT NULL,
  `Mecanico_idMecanico` INT UNSIGNED NOT NULL,
  `horasTrabajo` INT UNSIGNED NOT NULL,
  INDEX `fk_Mecanico_Servicio_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Mecanico_Servicio_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Servicio_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `TallerMecanico`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecanico_Servicio_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `TallerMecanico`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Proveedor` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Proveedor` (
  `idProveedor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Refaccion` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Refaccion` (
  `idRefaccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(7,2) UNSIGNED NOT NULL,
  `marca_refaccion` VARCHAR(100) NOT NULL,
  `modelo_refaccion` VARCHAR(100) NOT NULL,
  `Modelo_idModelo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRefaccion`),
  INDEX `fk_Refaccion_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  CONSTRAINT `fk_Refaccion_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `TallerMecanico`.`Modelo` (`idModelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Proveedor_Refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Proveedor_Refaccion` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Proveedor_Refaccion` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Proveedor_idProveedor` INT UNSIGNED NOT NULL,
  `Refaccion_idRefaccion` INT UNSIGNED NOT NULL,
  INDEX `fk_Proveedor_Refaccion_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  INDEX `fk_Proveedor_Refaccion_Refaccion1_idx` (`Refaccion_idRefaccion` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Proveedor_Refaccion_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `TallerMecanico`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedor_Refaccion_Refaccion1`
    FOREIGN KEY (`Refaccion_idRefaccion`)
    REFERENCES `TallerMecanico`.`Refaccion` (`idRefaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Movimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Movimientos` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Movimientos` (
  `idMovimientos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoMovimiento` ENUM('ENTRADA', 'SALIDA') NOT NULL,
  `cantidad` INT NOT NULL,
  `costos` DECIMAL(8,2) UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `Proveedor_Refaccion_id` INT UNSIGNED NULL,
  `Mecanico_idMecanico` INT UNSIGNED NULL,
  PRIMARY KEY (`idMovimientos`),
  INDEX `fk_Movimientos_Proveedor_Refaccion1_idx` (`Proveedor_Refaccion_id` ASC) VISIBLE,
  INDEX `fk_Movimientos_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Movimientos_Proveedor_Refaccion1`
    FOREIGN KEY (`Proveedor_Refaccion_id`)
    REFERENCES `TallerMecanico`.`Proveedor_Refaccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientos_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `TallerMecanico`.`Mecanico` (`idMecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Factura` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Factura` (
  `idFactura` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `TallerMecanico`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TallerMecanico`.`Servicio_Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TallerMecanico`.`Servicio_Factura` ;

CREATE TABLE IF NOT EXISTS `TallerMecanico`.`Servicio_Factura` (
  `Servicio_idServicio` INT NOT NULL,
  `Factura_idFactura` INT UNSIGNED NOT NULL,
  INDEX `fk_Servicio_Factura_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Servicio_Factura_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Factura_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `TallerMecanico`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_Factura_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `TallerMecanico`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `tallermecanico` ;

-- -----------------------------------------------------
-- Table `tallermecanico`.`anio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`anio` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`anio` (
  `idAnio` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `anio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAnio`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`cliente` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`cliente` (
  `idCliente` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `apellido` VARCHAR(120) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`costomanoobra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`costomanoobra` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`costomanoobra` (
  `idCostoManoObra` INT(10) UNSIGNED NOT NULL,
  `CostoManoObra` DECIMAL(7,2) UNSIGNED NOT NULL,
  `Fecha` DATE NOT NULL,
  PRIMARY KEY (`idCostoManoObra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`estado` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`estado` (
  `idEstado` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` ENUM('PROCESO', 'ESPERA', 'FINALIZADO') NULL DEFAULT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`factura` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`factura` (
  `idFactura` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `Cliente_idCliente` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `tallermecanico`.`cliente` (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`marca` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`marca` (
  `idMarca` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `Anio_idAnio` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marca_Anio1_idx` (`Anio_idAnio` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Anio1`
    FOREIGN KEY (`Anio_idAnio`)
    REFERENCES `tallermecanico`.`anio` (`idAnio`))
ENGINE = InnoDB
AUTO_INCREMENT = 97
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`mecanico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`mecanico` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`mecanico` (
  `idMecanico` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `apellido` VARCHAR(120) NOT NULL,
  `telefono` VARCHAR(100) NOT NULL,
  `CostoManoObra_idCostoManoObra` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idMecanico`),
  INDEX `fk_Mecanico_CostoManoObra1_idx` (`CostoManoObra_idCostoManoObra` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_CostoManoObra1`
    FOREIGN KEY (`CostoManoObra_idCostoManoObra`)
    REFERENCES `tallermecanico`.`costomanoobra` (`idCostoManoObra`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`servicio` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`servicio` (
  `idServicio` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `Estado_idEstado` INT(10) UNSIGNED NOT NULL,
  `kilometrage` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `tallermecanico`.`estado` (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`mecanico_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`mecanico_servicio` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`mecanico_servicio` (
  `Servicio_idServicio` INT(10) UNSIGNED NOT NULL,
  `Mecanico_idMecanico` INT(10) UNSIGNED NOT NULL,
  `horasTrabajo` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_Mecanico_Servicio_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Mecanico_Servicio_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanico_Servicio_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `tallermecanico`.`mecanico` (`idMecanico`),
  CONSTRAINT `fk_Mecanico_Servicio_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `tallermecanico`.`servicio` (`idServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`modelo` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`modelo` (
  `idModelo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `Marca_idMarca` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idModelo`),
  INDEX `fk_Modelo_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_Modelo_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `tallermecanico`.`marca` (`idMarca`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`proveedor` (
  `idProveedor` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`refaccion` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`refaccion` (
  `idRefaccion` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(7,2) UNSIGNED NOT NULL,
  `marca_refaccion` VARCHAR(100) NOT NULL,
  `modelo_refaccion` VARCHAR(100) NOT NULL,
  `Modelo_idModelo` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idRefaccion`),
  INDEX `fk_Refaccion_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  CONSTRAINT `fk_Refaccion_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `tallermecanico`.`modelo` (`idModelo`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`proveedor_refaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`proveedor_refaccion` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`proveedor_refaccion` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Proveedor_idProveedor` INT(10) UNSIGNED NOT NULL,
  `Refaccion_idRefaccion` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Proveedor_Refaccion_Proveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  INDEX `fk_Proveedor_Refaccion_Refaccion1_idx` (`Refaccion_idRefaccion` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_Refaccion_Proveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `tallermecanico`.`proveedor` (`idProveedor`),
  CONSTRAINT `fk_Proveedor_Refaccion_Refaccion1`
    FOREIGN KEY (`Refaccion_idRefaccion`)
    REFERENCES `tallermecanico`.`refaccion` (`idRefaccion`))
ENGINE = InnoDB
AUTO_INCREMENT = 501
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`movimientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`movimientos` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`movimientos` (
  `idMovimientos` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipoMovimiento` ENUM('ENTRADA', 'SALIDA') NOT NULL,
  `cantidad` INT(11) NOT NULL,
  `costos` DECIMAL(8,2) UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `Proveedor_Refaccion_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  `Mecanico_idMecanico` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`idMovimientos`),
  INDEX `fk_Movimientos_Proveedor_Refaccion1_idx` (`Proveedor_Refaccion_id` ASC) VISIBLE,
  INDEX `fk_Movimientos_Mecanico1_idx` (`Mecanico_idMecanico` ASC) VISIBLE,
  CONSTRAINT `fk_Movimientos_Mecanico1`
    FOREIGN KEY (`Mecanico_idMecanico`)
    REFERENCES `tallermecanico`.`mecanico` (`idMecanico`),
  CONSTRAINT `fk_Movimientos_Proveedor_Refaccion1`
    FOREIGN KEY (`Proveedor_Refaccion_id`)
    REFERENCES `tallermecanico`.`proveedor_refaccion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`servicio_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`servicio_factura` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`servicio_factura` (
  `Servicio_idServicio` INT(10) UNSIGNED NOT NULL,
  `Factura_idFactura` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_Servicio_Factura_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Servicio_Factura_Factura1_idx` (`Factura_idFactura` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Factura_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `tallermecanico`.`factura` (`idFactura`),
  CONSTRAINT `fk_Servicio_Factura_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `tallermecanico`.`servicio` (`idServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`vehiculo` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`vehiculo` (
  `idVehiculo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT(10) UNSIGNED NOT NULL,
  `Modelo_idModelo` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idVehiculo`),
  INDEX `fk_Vehiculo_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Vehiculo_Modelo1_idx` (`Modelo_idModelo` ASC) VISIBLE,
  CONSTRAINT `fk_Vehiculo_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `tallermecanico`.`cliente` (`idCliente`),
  CONSTRAINT `fk_Vehiculo_Modelo1`
    FOREIGN KEY (`Modelo_idModelo`)
    REFERENCES `tallermecanico`.`modelo` (`idModelo`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tallermecanico`.`vehiculo_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`vehiculo_servicio` ;

CREATE TABLE IF NOT EXISTS `tallermecanico`.`vehiculo_servicio` (
  `Vehiculo_idVehiculo` INT(10) UNSIGNED NOT NULL,
  `Servicio_idServicio` INT(10) UNSIGNED NOT NULL,
  INDEX `fk_vehiculo_servicio_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) VISIBLE,
  INDEX `fk_vehiculo_servicio_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_servicio_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `tallermecanico`.`servicio` (`idServicio`),
  CONSTRAINT `fk_vehiculo_servicio_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `tallermecanico`.`vehiculo` (`idVehiculo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `tallermecanico` ;

-- -----------------------------------------------------
-- Placeholder table for view `tallermecanico`.`marcas_por_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`marcas_por_proveedor` (`idProveedor` INT, `proveedor` INT, `marca` INT);

-- -----------------------------------------------------
-- Placeholder table for view `tallermecanico`.`refacciones_por_modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallermecanico`.`refacciones_por_modelo` (`id` INT, `refaccion` INT, `marca` INT, `modelo` INT, `automovil` INT);

-- -----------------------------------------------------
-- procedure clientBill
-- -----------------------------------------------------

USE `tallermecanico`;
DROP procedure IF EXISTS `tallermecanico`.`clientBill`;

DELIMITER $$
USE `tallermecanico`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `clientBill`(in IdC int)
BEGIN
SELECT 
factura.idFactura AS folio, 
factura.fecha AS fecha, 
CONCAT(cliente.nombre, ' ', cliente.apellido) AS cliente, 
CONCAT (marca.name, ' ', modelo.name, ' ', anio.anio) AS automovil,
servicio.kilometrage AS kilometraje,
mecanico_servicio.horasTrabajo AS horas,
servicio.nombre AS servicio,
costomanoobra.CostoManoObra AS costo,
costomanoobra.CostoManoObra * mecanico_servicio.horasTrabajo AS Total
FROM factura
JOIN cliente ON factura.Cliente_idCliente = cliente.idCliente
JOIN servicio_factura ON factura.idFactura = servicio_factura.Factura_idFactura
JOIN servicio ON servicio_factura.Servicio_idServicio = servicio.idServicio
JOIN vehiculo_servicio ON servicio.idServicio = vehiculo_servicio.Servicio_idServicio
JOIN vehiculo ON vehiculo_servicio.vehiculo_idVehiculo = vehiculo.idVehiculo
JOIN modelo ON vehiculo.modelo_idModelo = modelo.idModelo
JOIN marca ON modelo.marca_idMarca = marca.idMarca
JOIN anio ON marca.anio_idanio = anio.idAnio
JOIN mecanico_servicio ON servicio.idServicio = mecanico_servicio.Servicio_idServicio
JOIN mecanico ON mecanico_servicio.Mecanico_idMecanico = mecanico.idMecanico
JOIN costomanoobra ON mecanico.CostoManoObra_idCostoManoObra = costomanoobra.idCostoManoObra
WHERE cliente.idCliente = IdC;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function toKM
-- -----------------------------------------------------

USE `tallermecanico`;
DROP function IF EXISTS `tallermecanico`.`toKM`;

DELIMITER $$
USE `tallermecanico`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `toKM`(miles INT) RETURNS int(11)
    DETERMINISTIC
BEGIN
RETURN miles * 1.609344; 
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `tallermecanico`.`marcas_por_proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`marcas_por_proveedor`;
DROP VIEW IF EXISTS `tallermecanico`.`marcas_por_proveedor` ;
USE `tallermecanico`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tallermecanico`.`marcas_por_proveedor` AS select `tallermecanico`.`proveedor`.`idProveedor` AS `idProveedor`,`tallermecanico`.`proveedor`.`name` AS `proveedor`,group_concat(distinct `tallermecanico`.`refaccion`.`marca_refaccion` separator ',') AS `marca` from ((`tallermecanico`.`proveedor` join `tallermecanico`.`proveedor_refaccion` on((`tallermecanico`.`proveedor`.`idProveedor` = `tallermecanico`.`proveedor_refaccion`.`Proveedor_idProveedor`))) join `tallermecanico`.`refaccion` on((`tallermecanico`.`proveedor_refaccion`.`Refaccion_idRefaccion` = `tallermecanico`.`refaccion`.`idRefaccion`))) group by `tallermecanico`.`proveedor`.`idProveedor`;

-- -----------------------------------------------------
-- View `tallermecanico`.`refacciones_por_modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tallermecanico`.`refacciones_por_modelo`;
DROP VIEW IF EXISTS `tallermecanico`.`refacciones_por_modelo` ;
USE `tallermecanico`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `tallermecanico`.`refacciones_por_modelo` AS select `tallermecanico`.`refaccion`.`idRefaccion` AS `id`,`tallermecanico`.`refaccion`.`name` AS `refaccion`,`tallermecanico`.`refaccion`.`marca_refaccion` AS `marca`,`tallermecanico`.`refaccion`.`modelo_refaccion` AS `modelo`,concat(`tallermecanico`.`marca`.`name`,' ',`tallermecanico`.`modelo`.`name`,' ',`tallermecanico`.`anio`.`anio`) AS `automovil` from (((`tallermecanico`.`refaccion` join `tallermecanico`.`modelo` on((`tallermecanico`.`refaccion`.`Modelo_idModelo` = `tallermecanico`.`modelo`.`idModelo`))) join `tallermecanico`.`marca` on((`tallermecanico`.`modelo`.`Marca_idMarca` = `tallermecanico`.`marca`.`idMarca`))) join `tallermecanico`.`anio` on((`tallermecanico`.`marca`.`Anio_idAnio` = `tallermecanico`.`anio`.`idAnio`))) order by `tallermecanico`.`refaccion`.`idRefaccion`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
