-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 01:45:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db2` ;

-- -----------------------------------------------------
-- Schema db2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db2` DEFAULT CHARACTER SET utf8 ;
USE `db2` ;

-- -----------------------------------------------------
-- Table `db2`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db2`.`student` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(120) NULL,
  `last_name` VARCHAR(120) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db2`.`Maestros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db2`.`Maestros` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(120) NULL,
  `last_name` VARCHAR(120) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '								';


-- -----------------------------------------------------
-- Table `db2`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db2`.`materia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db2`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db2`.`relation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_id` INT UNSIGNED NOT NULL,
  `materia_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_relation_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `db2`.`student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relation_materia1`
    FOREIGN KEY (`materia_id`)
    REFERENCES `db2`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_relation_student1_idx` ON `db2`.`relation` (`student_id` ASC) VISIBLE;

CREATE INDEX `fk_relation_materia1_idx` ON `db2`.`relation` (`materia_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db2`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db2`.`curso` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Maestros_id` INT UNSIGNED NOT NULL,
  `relation_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_curso_Maestros1`
    FOREIGN KEY (`Maestros_id`)
    REFERENCES `db2`.`Maestros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_relation1`
    FOREIGN KEY (`relation_id`)
    REFERENCES `db2`.`relation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_curso_Maestros1_idx` ON `db2`.`curso` (`Maestros_id` ASC) VISIBLE;

CREATE INDEX `fk_curso_relation1_idx` ON `db2`.`curso` (`relation_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db2`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db2`.`grade` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Week` VARCHAR(15) NULL,
  `grade` TINYINT(2) NULL,
  `curso_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_grade_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db2`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_grade_curso1_idx` ON `db2`.`grade` (`curso_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
